apiVersion: v1
kind: Secret
metadata:
  name: genai-credentials
  labels:
    {{- include "coffeelovers.labels" . | nindent 4 }}
type: Opaque
stringData:
  openai-api-key: {{ required "secrets.openaiApiKey is required" .Values.secrets.openaiApiKey | quote }}
