apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffeelovers.postgresSecretName" . }}
  labels:
    {{- include "coffeelovers.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
