events {}

http {
    upstream auth_service {
        server auth-service:8081;
    }

    upstream trip_service {
        server trip-service:8082;
    }

    upstream genai_service {
        server genai:8001;
    }

    server {
        listen 8080;

        location /api/v1/auth/ {
            rewrite ^/api/v1/auth/(.*)$ /auth/$1 break;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/trips/ {
            rewrite ^/api/v1/trips/(.*)$ /trips/$1 break;
            proxy_pass http://trip_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/genai/ {
            proxy_pass http://genai_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /genai/health {
            proxy_pass http://genai_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}