apiVersion: v1
kind: Secret
metadata:
  name: auth-credentials
  labels:
    {{- include "coffeelovers.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
